from Xfig.check_if_function        import check_if_function
from Xfig.check_if_type_stat       import check_if_type_stat
from Xfig.find_coordinates         import find_coordinates
from Xfig.find_height              import find_height
from Xfig.find_width               import find_width
from Xfig.plot_all                 import plot_all
from Xfig.plot_all_spline          import plot_all_spline
from Xfig.plot_function            import plot_function
from Xfig.plot_fun_frame           import plot_fun_frame
from Xfig.plot_fun_name            import plot_fun_name
from Xfig.plot_fun_type_frame      import plot_fun_type_frame
from Xfig.plot_fun_type_name       import plot_fun_type_name
from Xfig.plot_fun_type_text_left  import plot_fun_type_text_left
from Xfig.plot_grid                import plot_grid
from Xfig.plot_legend              import plot_legend
from Xfig.plot_line                import plot_line
from Xfig.plot_meth_frame          import plot_meth_frame
from Xfig.plot_meth_name           import plot_meth_name
from Xfig.plot_meth_text_left      import plot_meth_text_left
from Xfig.plot_mod_end_compound    import plot_mod_end_compound
from Xfig.plot_mod_frame           import plot_mod_frame
from Xfig.plot_mod_name            import plot_mod_name
from Xfig.plot_mod_start_compound  import plot_mod_start_compound
from Xfig.plot_module              import plot_module
from Xfig.plot_prog_frame          import plot_prog_frame
from Xfig.plot_prog_name           import plot_prog_name
from Xfig.plot_program             import plot_program
from Xfig.plot                     import plot
from Xfig.plot_spline_legend       import plot_spline_legend
from Xfig.plot_spline              import plot_spline
from Xfig.plot_sub_frame           import plot_sub_frame
from Xfig.plot_sub_name            import plot_sub_name
from Xfig.plot_subroutine          import plot_subroutine
from Xfig.plot_text_center         import plot_text_center
from Xfig.plot_text_left           import plot_text_left
from Xfig.plot_text_right          import plot_text_right
from Xfig.plot_type_stat_frame     import plot_type_stat_frame
from Xfig.plot_type_stat           import plot_type_stat
from Xfig.plot_type_stat_text_left import plot_type_stat_text_left
from Xfig.plot_use_frame           import plot_use_frame
from Xfig.plot_use_name            import plot_use_name
from Xfig.plot_use_text_left       import plot_use_text_left
from Xfig.plot_var_frame           import plot_var_frame
from Xfig.plot_var_name            import plot_var_name
from Xfig.plot_var_text_left       import plot_var_text_left
from Xfig.use_len                  import use_len
from Xfig.walk                     import walk
from Xfig.write_header             import write_header
from Xfig.box_color                import box_color
from Xfig.font_code                import font_code
